name: "Test Linux"
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        api: [ 28 ]
        java_version: [ 17 ]
    steps:
      - name: kvm support
        run: |
          egrep -c '(vmx|svm)' /proc/cpuinfo
          id
          sudo adduser $USER kvm
          sudo chown -R $USER /dev/kvm
          id
      - uses: actions/checkout@v6
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java_version }}
      - name: test install-sdk
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v24 && npm install && npm ci && npm run build
        working-directory: install-sdk
      - name: test emulator-run-cmd
        run: npm config delete prefix && source ~/.nvm/nvm.sh && nvm install v24 && npm install && npm ci && npm run build
        working-directory: emulator-run-cmd
      - uses: ./install-sdk
        name: install sdk
      - run: sdkmanager platform-tools
      - run: adb devices
      - uses: ./emulator-run-cmd
        with:
          api: ${{ matrix.api }}
          tag: default
          abi: x86_64
          cmd: adb shell getprop
          bootTimeout: 500
          portNumber: 5555
      - uses: actions/upload-artifact@v4
        with:
          name: logcat-${{ matrix.os }}-${{ matrix.api }}
          path: artifacts/logcat.log
